name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Black style Lint
        uses: psf/black@stable
      - name: python-flake8
        uses: julianwachholz/flake8-action@v2.0.2
